services:

  backend:
    container_name: backend
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
      - database

volumes:
  db_volume

networks:
  backend:
  database:
